# Use root/example as user/password credentials
version: '3.1'

services:
  eventshuffle-api:
    image: node:23-alpine
    working_dir: /home/node
    volumes:
      - ./:/home/node
    command: ["node", "./src/index.js"]
